config/routes.rb
Rails.application.routes.draw do
  resources :tarefas
  root 'tarefas#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/evento.rb
class Evento < ApplicationRecord
  belongs_to :tarefa, class_name: "Tarefa", foreign_key: "tarefas_id"
  validates :tipo, :dados, presence: true

  MENSAGENS_FELIZ = ['parabéns, você completou a tarefa! :)',
                     'muito bem, você completou a tarefa!',
                     'é isso ai, você completou a tarefa! ;)',
                     'você completou a tarefa, continue assim!',
                     'você completou a tarefa, é assim que se faz! :)'
                    ]

  MENSAGENS_TRISTE = ['ah que pena, você não completou a tarefa!',
                      'oh não, você não completou a tarefa!',
                      'você não completou a tarefa, poxa vida! :(',
                      'você não completou a tarefa, tente novamente! :(',
                      'que triste, você não completou a tarefa :(',
                     ]
end

app/models/tarefa.rb
class Tarefa < ApplicationRecord
  has_many :eventos
  validates :descricao, presence: true
  validates :completa, inclusion: { in: [ true, false ] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
	
end

app/controllers/tarefas_controller.rb
class TarefasController < ApplicationController
  include ApplicationHelper

  before_action :current_tarefa, only: [:show, :edit, :update, :destroy]

  def index
    @tarefas = Tarefa.all
  end

  def show
  end

  def new
    @tarefa = Tarefa.new
  end

  def create
    tarefa = Tarefa.new(tarefa_params)
    if tarefa.save
      if tarefa_params[:completa] == '1'
        @mensagem = gerar_mensagem_feliz
        create_or_update_evento(tarefa, 'Congratulations', @mensagem)
      end
    else
      flash[:error] = 'falha ao criar tarefa!'
    end
    redirect_to tarefas_path
  end

  def edit
  end

  def update
    if @tarefa.update(tarefa_params)
      if tarefa_params[:completa] == '1'
        @mensagem = gerar_mensagem_feliz
      else
        @mensagem = gerar_mensagem_triste
      end
      @cor = @mensagem[:cor]
      flash[@cor] = @mensagem[:mensagem]
    else
      flash[:error] = 'falha ao atualizar tarefa!'
    end
    redirect_to tarefas_path
  end

  def destroy
    if @tarefa.destroy
      flash[:notice] = 'tarefa removida com sucesso!'
    else
      flash[:error] = 'falha ao remover tarefa!'
    end
    redirect_to tarefas_path
  end

  def create_or_update_evento(tarefa, tipo, dados)
    evento = Evento.where(tarefas_id: tarefa.id).first
    if evento
      evento.update(tipo: tipo, dados: dados)
    else
      Evento.create(tipo: tipo, dados: dados, tarefas_id: tarefa.id)
    end
  end

  def update_or_create!(tarefa, tipo, dados)
        assign_or_new(attributes).save!
  end

  private

  def tarefa_params
    params.require(:tarefa).permit(:descricao, :completa)
  end

  def current_tarefa
    @tarefa = Tarefa.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  CORES = ['#7B68EE', '#6A5ACD', '#800000', '#2F4F4F']

  def gerar_mensagem_feliz
    {
      mensagem: Evento::MENSAGENS_FELIZ.sample,
      cor: CORES.sample
    }
  end

  def gerar_mensagem_triste
    {
      mensagem: Evento::MENSAGENS_TRISTE.sample,
      cor: CORES.sample
    }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo Rails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tarefas/edit.html.erb
<!DOCTYPE html>
<html>
<header>
</header>
  <body>
    <div class="container pt-5">
      <section class="card col-md-8 offset-md-2 pt-3">
        <section class="py-4">
          <% flash.each do |key, value| %>
            <%= content_tag :div, value, class: "alert alert-warning flash #{key}" %>
          <% end %>
        </section>
        <%= link_to '', tarefas_path, class:"fa fa-arrow-left aria-hidden='true'" %>
        <div class="form-group pt-2">
          <h4>Edit taks</h4>
          <%= form_for @tarefa, url: {action: :update} do |f| %>
            <%= f.text_field :descricao, class:'form-control' %>
            <div class="pt-2">
              <%= f.label "taks complete?" %>
              <%= f.check_box :completa %>
            </div>
            <div class="pt-2">
              <%= f.submit 'Save', class: 'btn btn-primary' %>
            </div>
          <%end%>
        </div>
      </section>
    </div>
  </body>
</html>

app/views/tarefas/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo Rails</title>
  </head>
  <body>
    <div class="container">
      <div class="col-md-8 offset-md-2 pt-4">
        <h1>ToDo List</h1> 
        <section class="py-2">
          <div>
            <% flash.each do |key, value| %>
              <div style="color:<%= key %>">
                <a href="#" data-dismiss="alert">×</a>
                  <%= value %>
              </div>
            <% end %>
          </div>
        </section>
        <section class="pt-4">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>
                  Tasks
                </th>
              </tr>
            </thead>
            <tbody>
              <% @tarefas.each do |tarefa| %>
                <tr data-item-id=<%= "#{tarefa.id}" %> class="item">
                  <td><%= tarefa.descricao %></td>
                  <td><%= tarefa.completa %></td>
                  <td><%= link_to '', tarefa_path(tarefa), class: "fa fa-list aria-hidden='true'"%></td>
                  <td><%= link_to '', edit_tarefa_path(tarefa.id),class: "fa fa-pencil aria-hidden='true'"%></td>
                  <td><%= link_to '<i class="fa fa-trash" aria-hidden="true"></i>
                  '.html_safe, { action: :destroy, id: tarefa.id }, method: :delete, data: { confirm: 'Are you sure?' }%></td>
              <% end %>
            </tbody>
          </table>
        </section>
        <section>
          <ul class="nav nav-pills">
            <li class="nav-item pr-4">
              <%=link_to 'New toDo', new_tarefa_path, class: 'btn btn-primary'%>
            </li>
            <li class="nav-item pr-4">
              <%=link_to 'Export List', new_tarefa_path, class: 'btn btn-primary'%>
            </li>
          </ul>
        </section>
      </div>
    </div>
  </body>
</html>

app/views/tarefas/new.html.erb
<!DOCTYPE html>
<html>
<header>
</header>
  <body>
    <div class="container pt-5">
      <section class="card col-md-8 offset-md-2 pt-3">
        <section class="py-4">
          <% flash.each do |key, value| %>
            <%= content_tag :div, value, class: "alert alert-warning flash #{key}" %>
          <% end %>
        </section>
        <%= link_to '',tarefas_path , class: "fa fa-arrow-left aria-hidden='true'"  %>
        <div class="form-group pt-2">
          <h4>Adicionar tarefa</h4>
          <%= form_for @tarefa, url: {action: :create} do |f| %>
            <%= f.text_field :descricao, class:'form-control' %>
            <div class="pt-2">
              <%= f.label "Esta tarefa está completa?" %>
              <%= f.check_box :completa %>
            </div>
            <div class="pt-2">
              <%= f.submit 'Salvar', class: 'btn btn-primary' %>
            </div>
          <%end%>
        </div>
      </section>
    </div>
  </body>
</html>

app/views/tarefas/show.html.erb
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <div class="container pt-5">
      <section class="card col-md-8 offset-md-2">
        <%= link_to '', tarefas_path,class:"fa fa-arrow-left aria-hidden='true'" %>
        <h3 class="mx-auto">Detail</h3>
        <p>Task: <%=@tarefa.descricao%></p>
        <p>Complete?: <%=@tarefa.completa == true ? 'Yes' : 'No' %></p>
      </section>
    </div>
  </body>
</html>